
workflows:
  react-native-app:
    name: React Native Android & iOS Build
    max_build_duration: 60
    environment:
      groups:
        - react-native
        # Example: Add your own API keys here
        # API_URL: $API_URL
      node: 20.11.1
      npm: 10.5.0
      xcode: latest
      java: 17
      flutter: stable
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build Android APK (Release)
        script: |
          flutter clean
          flutter build apk --release
      - name: Build iOS (Simulator .app)
        script: |
          cd ios
          pod install
          xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -configuration Release -sdk iphonesimulator -derivedDataPath build
          cd ..
      # To build .ipa for real devices, you need proper signing setup. Uncomment and configure below if needed:
      # - name: Build iOS .ipa (for App Store/TestFlight)
      #   script: |
      #     cd ios
      #     xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -configuration Release -sdk iphoneos -archivePath $CM_BUILD_DIR/YourApp.xcarchive archive
      #     xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/YourApp.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $CM_BUILD_DIR/YourApp
      #     cd ..

    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - ios/build/Build/Products/Release-iphonesimulator/*.app
      # - $CM_BUILD_DIR/YourApp/*.ipa # Uncomment if exporting .ipa above

    publishing:
      email:
        recipients:
          - iamsmarajit@outlook.com
      notify:
        on_success: true
        on_failure: true

# Setup notes:
# 1. Place this file at the root of your project as codemagic.yaml
# 2. Replace "YourApp" with your actual Xcode workspace and scheme names
# 3. iOS .ipa export needs Apple Dev credentials if publishing
