workflows:
  web-release:
    name: Release build for React Web App
    environment:
      node: 20.11.1
      npm: 10.5.0
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web app
        script: npm run build
    artifacts:
      - build/**