workflows:
  android-build:
    name: Build Android APK
    environment:
      node: 20.11.1
      npm: 10.5.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
          cd ..
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk